'use client';

import { useEffect, useRef, useState } from 'react';
import EditorialHero from './components/EditorialHero';
import OurBusiness from './components/OurBusiness';
import { AnimatePresence, MotionConfig, motion, useInView, useIsPresent, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowRight, ArrowDown, Menu, X, Leaf, Sprout, Droplets, Users, ShieldCheck, Package, ShoppingBag, MapPin, Download, Plus, Check, Mail, Phone, MoveUpRight, TreePalm, Facebook, Instagram, Linkedin } from 'lucide-react';

const photo = (id: string, width = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const images = { hero: photo('photo-1512067954-9c6c25359231',2400), coconut: photo('photo-1589810353876-0497a89e5ad1',800), rubber: photo('photo-1441974231531-c6227db76b6e',800), fruit: photo('photo-1619566636858-adf3ef46400b',800), spices: photo('photo-1506368249639-73a05d6f6488',800), coffee: photo('photo-1447933601403-0c6688de566e',800), intercrops: photo('photo-1500382017468-9049fed747ef',800), forest: photo('photo-1473448912268-2022ce9509d8',1600), estate: photo('photo-1512067954-9c6c25359231',1200) };
const estates = [ {name:'Attanagalla',district:'Gampaha',crops:'Coconut · Rubber · Fruits',hectares:'640',x:49,y:70,image:images.rubber}, {name:'Dambadeniya',district:'Kurunegala',crops:'Coconut · Spices',hectares:'720',x:42,y:53,image:images.intercrops}, {name:'Dodangaslanda',district:'Kurunegala',crops:'Coconut · Rubber · Coffee',hectares:'810',x:65,y:38,image:images.forest}, {name:'Hiriyala',district:'Kurunegala',crops:'Coconut · Fruits · Intercrops',hectares:'860',x:59,y:24,image:images.intercrops}, {name:'Katugampola',district:'Kurunegala',crops:'Coconut · Intercrops',hectares:'690',x:27,y:43,image:images.hero}, {name:'Kurunegala',district:'Kurunegala',crops:'Coconut · Fruits · Spices',hectares:'780',x:53,y:43,image:images.estate}, {name:'Narammala',district:'Kurunegala',crops:'Coconut · Fruits',hectares:'600',x:35,y:61,image:images.intercrops} ];
const navigation = [['Home','home'],['About','about'],['Estates','estates'],['Our Business','business'],['Sustainability','sustainability'],['Publications','publications'],['News','news'],['Contact','contact']];

const calmEase = [0.22, 1, 0.36, 1] as const;

function Reveal({ children, className = '', delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ type: 'tween', duration: reduced ? 0 : 0.46, delay: reduced ? 0 : delay, ease: calmEase }}>{children}</motion.div>;
}

function Stat({ value, suffix, label, index }: { value: number; suffix: string; label: string; index: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const numberRef = useRef<HTMLSpanElement>(null);
  const visible = useInView(ref, { once: true, amount: 0.45 });
  const reduced = useReducedMotion();
  const finalValue = value.toLocaleString('en-US');

  useEffect(() => {
    const element = numberRef.current;
    if (!element) return;
    if (!visible || reduced !== false) { element.textContent = finalValue; return; }
    let previous = -1;
    let frame: number;
    let started: number | undefined;
    const tick = (now: number) => {
      started ??= now;
      const progress = Math.min((now - started) / 1200, 1);
      const rounded = Math.round(value * (1 - Math.pow(1 - progress, 3)));
      if (rounded !== previous) {
        element.textContent = rounded.toLocaleString('en-US');
        previous = rounded;
      }
      if (progress < 1) frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [visible, reduced, value, finalValue]);

  return <div className="stat" ref={ref}><span className="tiny-number">{index}</span><div className="stat-value"><span className="sr-only">{finalValue}{suffix}</span><span aria-hidden="true" className="stat-digits"><span className="stat-width">{finalValue}{suffix}</span><span className="stat-animated"><span ref={numberRef}>{finalValue}</span>{suffix}</span></span><span aria-hidden="true" className="stat-star">✳</span></div><p>{label}</p></div>;
}

function EstateTransition({ children }: { children: React.ReactNode }) {
  const reduced = useReducedMotion();
  const present = useIsPresent();
  return <motion.div aria-hidden={!present} className="estate-panel" initial={reduced ? false : { opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 0, transition: { duration: reduced ? 0 : 0.16 } }} transition={{ type: 'tween', duration: reduced ? 0 : 0.26, ease: calmEase }} style={{ zIndex: present ? 1 : 0, pointerEvents: present ? 'auto' : 'none' }}>{children}</motion.div>;
}
function Brand({light=false}:{light?:boolean}) {return <a href="#home" aria-label="Kurunegala Plantations Limited home" className={`brand ${light?'brand-light':''}`}><span className="brand-mark"><TreePalm strokeWidth={1.25}/></span><span>KURUNEGALA<small>PLANTATIONS LIMITED</small></span></a>;}

export default function Home() {
const [menu,setMenu]=useState(false);const [active,setActive]=useState(5);const [notice,setNotice]=useState<string|null>(null);const estate=estates[active];
const reducedMotion = useReducedMotion();
const headerMarker = useRef<HTMLSpanElement>(null);
const headerAtTop = useInView(headerMarker, { initial: true });
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),5500);return()=>clearTimeout(timer);},[notice]);
useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);setNotice(null);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
const demoStore=()=>setNotice('Our online store is being previewed in this concept. Product enquiries can be made through the contact section.');
return <MotionConfig reducedMotion="user" transition={{ type: 'tween', duration: reducedMotion ? 0 : 0.2, ease: calmEase }}>
<a className="skip-link" href="#main">Skip to content</a>
<header className={['header cinematic-header', !headerAtTop || menu ? 'header-solid' : ''].join(' ')}><div className="header-inner"><Brand/><nav aria-label="Main navigation" className="desktop-nav">{navigation.map(([name,id])=><a key={id} href={`#${id}`}>{name}</a>)}</nav><a className="store-button" href="#products"><ShoppingBag size={15}/><span>Online Store</span><ArrowUpRight size={15}/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-nav">{menu?<X/>:<Menu/>}</button></div><AnimatePresence>{menu&&<motion.nav id="mobile-nav" aria-label="Mobile navigation" className="mobile-nav" initial={reducedMotion ? false : {opacity:0,y:-4}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-4}}>{navigation.map(([name,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{name}<ArrowUpRight size={16}/></a>)}</motion.nav>}</AnimatePresence></header>
<main id="main">
<EditorialHero headerMarker={headerMarker} />
<OurBusiness />
<section id="about" className="intro wrap section"><Reveal className="intro-heading"><div className="eyebrow"><span/>KPL AT A GLANCE</div><h2>Our roots run deep.<br/><span className="muted">Our vision looks ahead.</span></h2></Reveal><Reveal className="intro-copy"><p>From the coconut groves of the North Western Province to the fertile landscapes beyond, we connect the potential of our land with the needs of tomorrow.</p><p className="small-copy">Kurunegala Plantations Limited brings people, agriculture and responsible enterprise together.</p><a href="#business" className="text-link">Discover what we grow <ArrowUpRight size={17}/></a></Reveal><Reveal className="stats"><Stat index="01" value={7} suffix="" label="Area Estates"/><Stat index="02" value={3} suffix="" label="Districts"/><Stat index="03" value={5000} suffix="+" label="Hectares Managed"/><Stat index="04" value={15} suffix="M+" label="Coconuts Annually"/></Reveal><p className="data-note">Figures supplied for this concept; subject to confirmation.</p></section>
<section id="estates" className="estates section"><div className="wrap"><Reveal className="section-heading"><div><div className="eyebrow light"><span/>EXPLORE OUR ESTATES</div><h2>Seven estates.<br/><em>One enduring connection.</em></h2></div><p>Different landscapes, connected by the care<br/>we bring to every hectare. Explore our estates.</p></Reveal><Reveal className="estate-explorer"><div className="estate-map"><div className="map-label">OUR LANDSCAPE <span>01 — 07</span></div><svg viewBox="0 0 400 430" className="map-contours" aria-hidden="true"><path d="M166 29 231 48 252 86 301 123 318 183 289 220 310 286 278 331 231 367 186 405 134 384 111 333 70 310 80 252 57 208 83 153 105 111 115 66Z"/><path d="M169 58 213 79 224 116 265 150 270 187 248 224 269 279 236 312 200 350 157 358 145 306 107 283 114 237 92 205 113 167 135 122Z"/><path d="M172 96 193 133 229 165 222 201 216 235 231 272 196 302 171 314 166 278 142 257 149 215 129 195 153 154Z"/><path className="map-road" d="M165 380Q220 300 184 240T211 126L197 58M83 225Q182 180 290 210M111 314Q140 240 282 144"/></svg><div className="map-pins">{estates.map((item,i)=><button key={item.name} className={`map-pin ${active===i?'selected':''}`} style={{left:`${item.x}%`,top:`${item.y}%`}} onClick={()=>setActive(i)} aria-label={`Select ${item.name} estate`} aria-pressed={active===i}><span/>{active===i&&<b>{item.name}</b>}</button>)}</div><div className="map-caption"><span className="location-dot"/> SELECT AN ESTATE TO EXPLORE</div><span className="map-disclaimer">Schematic illustration · not to scale</span></div><div className="estate-detail"><div className="estate-tabs" role="group" aria-label="Select an estate">{estates.map((item,i)=><button key={item.name} onClick={()=>setActive(i)} className={i===active?'active':''} aria-pressed={i===active}>{item.name}</button>)}</div><div className="estate-panel-stage"><AnimatePresence initial={false} mode="sync"><EstateTransition key={estate.name}><img src={estate.image} alt={`Illustrative green landscape for ${estate.name} estate`} loading="lazy"/><div className="estate-panel-content"><div className="estate-title"><div><span className="eyebrow">AREA ESTATE / 0{active+1}</span><h3>{estate.name}</h3></div><MapPin size={24} strokeWidth={1}/></div><div className="estate-facts"><div><small>LOCATION</small><p>{estate.district} District</p></div><div><small>LAND AREA</small><p>{estate.hectares} hectares</p></div><div className="crop-fact"><small>PRIMARY CROPS</small><p>{estate.crops}</p></div></div><span className="sample-label">Illustrative estate information for this demo.</span></div></EstateTransition></AnimatePresence></div></div></Reveal></div></section>
<section className="journey section wrap"><Reveal className="section-heading"><div><div className="eyebrow"><span/>FROM ESTATE TO CONSUMER</div><h2>Care, at every step.</h2></div><p>A considered journey from the soil beneath<br/>our feet to the products in your hands.</p></Reveal><Reveal className="process">{[{name:'Cultivation',icon:Sprout,text:'Nurturing the land'},{name:'Harvesting',icon:Leaf,text:'Gathering with care'},{name:'Processing',icon:Package,text:'Preserving natural value'},{name:'Quality Assurance',icon:ShieldCheck,text:'Attention to every detail'},{name:'Consumer',icon:ShoppingBag,text:'Bringing nature closer'}].map((step,i)=><div className="process-step" key={step.name}><div className="process-top"><span className="process-icon"><step.icon strokeWidth={1.2} size={27}/></span>{i<4&&<ArrowRight className="process-arrow" size={18}/>}</div><small>0{i+1}</small><h3>{step.name}</h3><p>{step.text}</p></div>)}</Reveal></section>
<section id="sustainability" className="sustainability"><img className="sustainability-image" src={images.forest} alt="Sunlight falling through a thriving green forest" loading="lazy"/><div className="sustainability-shade"/><div className="wrap section sustainability-content"><Reveal className="sustainability-heading"><div className="eyebrow light"><span/>GROWING RESPONSIBLY</div><h2>A thriving business begins<br/>with a <em>thriving planet.</em></h2><p>Our future is inseparable from the land we cultivate<br className="desktop-break"/> and the communities who call it home.</p></Reveal><div className="sustainability-grid">{[{icon:Sprout,title:'Sustainable Agriculture',text:'Caring for soil health and cultivating with the long term in mind.'},{icon:Leaf,title:'Biodiversity',text:'Making space for the rich natural life within our landscapes.'},{icon:Droplets,title:'Water Management',text:'Valuing every drop through mindful use of water resources.'},{icon:Users,title:'Community Development',text:'Growing together with the people at the heart of our estates.'}].map(item=><Reveal key={item.title} className="sustainability-card"><item.icon size={26} strokeWidth={1.3}/><h3>{item.title}</h3><p>{item.text}</p></Reveal>)}</div></div></section>
<section id="products" className="products section wrap"><Reveal className="section-heading"><div><div className="eyebrow"><span/>NATURALLY, FROM OUR ESTATES</div><h2>A little of our land.<br/>A part of your everyday.</h2></div><button onClick={demoStore} className="button button-outline">Visit Online Store<ArrowUpRight size={17}/></button></Reveal><div className="products-grid">{[{name:'Fresh Coconut',category:'ESTATE FRESH',image:images.coconut,desc:'A tropical everyday essential.'},{name:'Pure Coconut Oil',category:'PANTRY ESSENTIALS',image:photo('photo-1474979266404-7eaacbcd87c5',800),desc:'Simple goodness for your kitchen.'},{name:'Ceylon Spices',category:'THE FLAVOURS OF SRI LANKA',image:images.spices,desc:'Aromatic by nature.'}].map(item=><Reveal key={item.name} className="product-card"><div className="product-image"><img src={item.image} loading="lazy" alt={item.name}/><span>PRODUCT PREVIEW</span><button onClick={()=>setNotice(`${item.name}: ${item.desc} This product is an illustrative preview; ordering is not enabled.`)} aria-label={`View ${item.name} details`}><Plus size={20}/></button></div><span className="eyebrow">{item.category}</span><h3>{item.name}</h3><p>{item.desc}</p></Reveal>)}</div></section>
<section id="publications" className="publications section"><div className="wrap"><Reveal className="section-heading"><div><div className="eyebrow"><span/>PUBLICATIONS</div><h2>A clear view of our progress.</h2></div><p>Explore our annual reporting.<br/>Presented here as sample publications.</p></Reveal><div className="reports-grid">{['2025','2024','2023'].map((year,i)=><Reveal key={year} className="report-card"><div className={`report-cover cover-${i}`}><TreePalm size={32} strokeWidth={1}/><span>KURUNEGALA<br/>PLANTATIONS LIMITED</span><div><small>ANNUAL REPORT</small><strong>{year}</strong></div><span className="cover-line"/><small className="report-sample">CONCEPT COVER</small></div><div className="report-info"><div><span>ANNUAL REPORT</span><h3>{year}</h3></div><button onClick={()=>setNotice(`Annual Report ${year} is a demo placeholder. No official report is attached.`)} aria-label={`Download annual report ${year} (demo)`}><Download size={20}/></button></div></Reveal>)}</div></div></section>
<section id="news" className="news section wrap"><Reveal className="section-heading"><div><div className="eyebrow"><span/>NEWS & PERSPECTIVES</div><h2>Stories from our landscape.</h2></div><span className="editorial-note">SAMPLE EDITORIAL CONTENT</span></Reveal><div className="news-grid">{[{date:'18 JUNE 2025',tag:'FROM THE ESTATES',title:'A closer look at the life of a coconut estate',image:images.hero,body:'From young palms to mature groves, every stage of cultivation calls for patience and care. This sample story introduces the everyday work that connects people, land and produce.'},{date:'05 JUNE 2025',tag:'SUSTAINABILITY',title:'Cultivating a future in harmony with nature',image:images.forest,body:'Healthy landscapes are the foundation of agriculture. This illustrative article explores soil care, biodiversity and thoughtful water use as themes for future sustainability reporting.'},{date:'22 MAY 2025',tag:'OUR PEOPLE',title:'The people behind every harvest',image:images.intercrops,body:'Plantation life is shaped by the knowledge and commitment of its people. This sample editorial offers a place to share authentic employee and community stories in the final website.'}].map(item=><Reveal key={item.title}><button className="news-card" onClick={()=>setNotice(item.body)}><div className="news-image"><img src={item.image} alt={item.title} loading="lazy"/><span className="round-arrow"><ArrowUpRight size={20}/></span></div><div className="news-meta"><span>{item.tag}</span><time>{item.date}</time></div><h3>{item.title}</h3><span className="news-read">Read sample story <ArrowRight size={15}/></span></button></Reveal>)}</div></section>
<section id="contact" className="contact"><div className="wrap"><Reveal className="contact-inner"><div><div className="eyebrow light"><span/>LET’S GROW TOGETHER</div><h2>Connect with<br/>Kurunegala Plantations Limited</h2></div><a className="contact-circle" href="mailto:contact@kpl.example" aria-label="Email Kurunegala Plantations (placeholder address)"><ArrowUpRight size={34} strokeWidth={1}/></a></Reveal><p className="contact-note">Demo contact: contact@kpl.example · Official contact details to be confirmed.</p></div></section>
</main>
<footer className="footer"><div className="wrap footer-grid"><div className="footer-brand"><Brand/><p>Rooted in the land.<br/>Committed to tomorrow.</p><div className="socials">{[{icon:Facebook,name:'Facebook'},{icon:Instagram,name:'Instagram'},{icon:Linkedin,name:'LinkedIn'}].map(item=><button key={item.name} aria-label={`${item.name} (demo)`} onClick={()=>setNotice(`The official ${item.name} profile will be linked in the final website.`)}><item.icon size={17}/></button>)}</div></div><div><h4>EXPLORE</h4><a href="#about">About KPL</a><a href="#estates">Our Estates</a><a href="#business">Our Business</a><a href="#sustainability">Sustainability</a></div><div><h4>RESOURCES</h4><a href="#publications">Publications</a><a href="#news">News & Perspectives</a><a href="#products">Online Store</a><a href="#contact">Contact Us</a></div><div className="footer-contact"><h4>GET IN TOUCH</h4><p><MapPin size={16}/>Kurunegala, Sri Lanka<br/>Office address to be confirmed</p><a href="mailto:contact@kpl.example"><Mail size={16}/>contact@kpl.example</a><p><Phone size={16}/>Telephone to be confirmed</p></div></div><div className="wrap footer-bottom"><p>© {new Date().getFullYear()} Kurunegala Plantations Limited. Concept presentation.</p><a href="#home">BACK TO TOP <MoveUpRight size={13}/></a></div></footer>
<div className="demo-label"><span/>Concept Demo – For Evaluation Only</div>
<AnimatePresence>{notice&&<motion.div role="status" className="notice" initial={reducedMotion ? false : {opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,y:6}}><Check size={20}/><p>{notice}</p><button onClick={()=>setNotice(null)} aria-label="Dismiss notification"><X size={18}/></button></motion.div>}</AnimatePresence>
</MotionConfig>;
}
